### ISSUE TITLE
Feature: add support for database without authorization

### ISSUE THREAD

**Issue by pva** [avast/mongodb-oplog-stats#2]
I'm trying to connect to the database without supplied user and this fails:

```
 ./mongodb-oplog-stats --host 10.254.253.110
Obtaining stats (limit: 100)...
error: oplog query failed
  cause: Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: 10.254.253.110:27017, Type: Unknown, Error: SCRAM failure: no username supplied }, ] }
backtrace:
```

We have not enabled authorization and thus mongo client connects fine:
```
mongo --host mongo1
MongoDB shell version v4.2.18
connecting to: mongodb://mongo1:27017/?compressors=disabled&gssapiServiceName=mongodb
...
```

Probably, some simple fix is possible for this issue in case a user was not supplied.

**Comment by s3rvac** [comment]
Hi, thank you for the report. I have added support for connecting to MongoDB databases with disabled authentication (commit b8eacb7d8423e03e682ffeff046816f0224537a9). If you stumble upon any other issues, please let me know.
